### ISSUE TITLE
PointerPath for TerritoryType in 2019.10.24.0000.0000 seems to be wrong

### ISSUE THREAD

**Issue by TheFuzzy** [goaaats/Nhaama#2]
The current PointerPath (`29348096, 1632`) resolves to `0`. I tried the following and it worked for me.

```json
  "TerritoryType": {
    "PointerPath": [
		29693520,
		10
    ],
    "Module": {
      "ModuleName": "ffxiv_dx11.exe"
    }
  },
```

I don't actually know if it'll work for your main use case (the Discord Rich Presence add-on), as I use a custom build of the RichPresenceRunner.

**Comment by goaaats** [comment]
Hey, thanks a bunch! 5.1 been a bit messy, should work now!
